local animations = {
    ashen_azalea = { "awaken", "death", "falling", "go_sleep", "ground_breaking", "idle", "jump", "sleep", "stomp", "walk" },
    beluga = { "bite", "body", "dying", "feedme", "feedstart", "nomnom", "swimming" },
    black_angler_fish = { "bite", "death", "idle", "walk" },
    cerberus = { "attack_1", "dash", "death", "firebreath", "idle", "leap_turn", "melee_1", "melee_2", "meteor", "passive", "rib", "roar", "stomp_left", "stomp_right", "stun", "walk" },
    circular_branch = { "skill" },
    deep_angler_fish = { "bite", "death", "idle", "walk" },
    ecabyssosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown ", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecamonite = { "body", "dying", "swimeat", "swimming" },
    ecaquilolamna = { "body", "dying", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecaquilolamnababy = { "body", "dying", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecarchelon = { "body", "dying", "swimatt1", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecatopodentatus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecbabyaquilolamna = { "body", "dying", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecbabyelasmosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecbabymosasaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingloop", "swimmingup", "swimmingupend" },
    ecbabyophthalmosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecbabyplesiosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecbabyshastasaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingloop", "swimmingup", "swimmingupend" },
    eccartornychus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecclidastes = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    eccoelacanth = { "body", "dying", "swimeat", "swimming" },
    eccogboundicarosphinx = { "attack1", "attack2", "attack3", "attack4", "body", "dying", "fall", "fallbody", "fallend", "fallstart", "flybreath", "flycharge", "flying", "groundbreath", "landing", "takeoff", "waiting", "walking" },
    ecdunkleosteus = { "body", "dying", "swimatt1", "swimatt2", "swimatt3", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecdunkleosteusbaby = { "body", "dying", "swimatt1", "swimatt2", "swimatt3", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecelasmosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecelasmosaurusbaby = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecichtyosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecleedsichthys = { "body", "dying ", "swimatt1", "swimatt2", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop", "whalejump" },
    ecleviathan = { "body", "dying ", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop", "whalejump" },
    ["ec-leviathan"] = { "death", "idle", "launch", "on_spawn", "run", "scales", "tail", "vortex", "walk", "wreck", "wreck_show" },
    ["ec-leviathan_seg"] = { "bite", "idle", "show", "walk", "walkww" },
    ecleviathanbaby = { "body", "dying ", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop", "whalejump" },
    ecliopleurodon = { "body", "dying", "shipjump", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown ", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecliopleurodonbaby = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown ", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecmosasaurus = { "body", "dying", "shipjump", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingloop", "swimmingup", "swimmingupend" },
    ecmosasaurusbaby = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingloop", "swimmingup", "swimmingupend" },
    ecophthalmosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimatt3", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecplesiosaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecplesiosaurusbaby = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingup", "swimmingupend", "swimminguploop" },
    ecseascorpion = { "body", "dying", "swimeat", "swimming" },
    ecshastasaurus = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingend", "swimmingloop", "swimmingup", "waiting" },
    ecshastasaurusbaby = { "body", "dying", "swimatt1", "swimatt2", "swimeat", "swimming", "swimmingdown", "swimmingdownend", "swimmingdownloop", "swimmingloop", "swimmingup", "swimmingupend" },
    em_dskeleton_archer = { "aim_resume", "aim_start", "aim_start_legs", "archering", "attack1", "attack1_resources", "attack1_torso", "death", "death2", "draw_start_old", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_aiming", "idle_combat", "idle_combat_stance", "laniakea", "POSE============", "shoot1", "shoot1_legs", "shoot1_old", "shoot2", "spawned", "walk", "walk_aiming", "walk_backwards", "walk_backwards_legs", "walk_combat", "walk_fast", "walk_fast_aiming", "walk_left", "walk_movement_Aiming(10)", "walk_movement_combat(-35)", "walk_movement_combat(40)", "walk_movement_run(60)", "walk_movement_run(75)", "walk_movement_walk(17.5)", "walk_right", "walk_sideways", "walkfast_aiming_start", "walkfast_aiming_start_reosurces" },
    em_dskeleton_firexplosion_vfx = { "explode" },
    em_dskeleton_footman = { "attack1_left", "attack1_resources", "attack1_right", "death", "death2", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_combat", "POSE============", "spawned", "walk", "walk_70(unused)", "walk_backwards", "walk_combat", "walk_fast", "walk_movement_combat(-20)", "walk_movement_combat(25)", "walk_movement_run(45)", "walk_movement_walk(35" },
    em_dskeleton_halberdier = { "attack1", "attack1_resources", "attack1_running", "attack2", "attack2_resources", "death", "death2", "death3", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_combat", "POSE============", "spawned", "walk", "walk_backwards", "walk_combat", "walk_fast", "walk_movement_combat(-20)", "walk_movement_combat(25)", "walk_movement_run(45)", "walk_movement_walk(17.5)" },
    em_dskeleton_swordman = { "attack1", "attack1_resources", "attack2", "attack2_resources", "death", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_combat", "POSE============", "spawned", "walk", "walk_70(unused)", "walk_backwards", "walk_combat", "walk_fast", "walk_movement_combat(-20)", "walk_movement_combat(25)", "walk_movement_run(45)", "walk_movement_walk(35" },
    em_dskeleton_tank = { "attack1", "attack1_blocking", "attack1_resources", "attack2", "attack2_blocking", "attack2_resources", "death", "death2", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_blocking", "idle_combat", "POSE============", "quickblock1_a", "quickblock1_b", "quickblock1_c", "quickblock1_d", "quickblock1_e", "quickblock2_a", "quickblock2_b", "quickblock2_c", "quickblock2_d", "quickblock2_e", "quickblock3_a", "quickblock3_b", "quickblock3_c", "spawned", "walk", "walk_backwards", "walk_blocking", "walk_combat", "walk_fast", "walk_movement_blocking(15)", "walk_movement_combat(20)", "walk_movement_combat(-20)", "walk_movement_run(45)", "walk_movement_walk(17.5)" },
    em_dskeleton_variations = { "attack1", "attack1_left", "attack1_resources", "attack1_resources2", "attack1_right", "attack2", "attack2_resources", "death", "death2", "hurt1", "hurt2", "hurt3", "hurt4", "hurt5", "hurt6", "hurt7", "hurt8", "hurtbad1", "hurtbad2", "hurtbad3", "hurtbad4", "idle", "idle_combat", "idle_combat2", "idle2", "POSE============", "POSE============2", "walk", "walk_70(unused)", "walk_70(unused)2", "walk_backwards", "walk_backwards2", "walk_combat", "walk_combat2", "walk_fast", "walk_fast2", "walk_movement_combat(-20)", "walk_movement_combat(-20)2", "walk_movement_combat(25)", "walk_movement_combat(25)2", "walk_movement_run(45)", "walk_movement_run(45)2", "walk_movement_walk(2", "walk_movement_walk(35", "walk2" },
    em_dskeleton_warrior = { "attack1", "attack1_blocking", "attack1_resources", "attack2", "attack2_blocking", "attack2_resources", "block_trigger1", "block_trigger2", "block_trigger3", "death", "death2", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_blocking", "idle_combat", "POSE============", "quickblock1_a", "quickblock1_b", "quickblock1_c", "quickblock1_d", "quickblock1_e", "quickblock2_a", "quickblock2_b", "quickblock2_c", "quickblock2_d", "quickblock2_e", "quickblock3_a", "quickblock3_b", "quickblock3_c", "spawned", "walk", "walk_70(unused)", "walk_backwards", "walk_blocking", "walk_combat", "walk_fast", "walk_movement_combat(-20)", "walk_movement_combat(25)", "walk_movement_run(45)", "walk_movement_walk(17.5)" },
    em_dskeleton_wizard = { "attack1", "attack1_resources", "attack2", "attack2_resources", "death", "death2", "hurt1", "hurt2", "hurt3", "hurt4", "hurtbad1", "hurtbad2", "idle", "idle_combat", "laniakea", "POSE============", "spawned", "spell1", "spell2", "walk", "walk_backwards", "walk_backwards_legs", "walk_combat", "walk_fast", "walk_left", "walk_movement_combat(20)", "walk_movement_combat(-20)", "walk_movement_run(30)", "walk_movement_walk(35", "walk_right", "walk_sideways" },
    em_dskeleton_wizard_death = { "death", "death2" },
    em_dskeleton_wizardshield = { "explode", "spawn" },
    em_dsw_fireball = { "idle" },
    ent_branch = { "skill" },
    ent_branch_upwards = { "skill" },
    ent_king = { "death", "idle", "left_punch", "right_punch", "rise", "shout", "stomp", "walk" },
    ent_minion = { "attack", "death", "idle", "spawn", "walk" },
    ent_sorcerer = { "attack1", "attack2", "death", "idle", "walk" },
    ent_warrior = { "attack1", "attack2", "death", "idle", "walk" },
    frostmite = { "attack", "charge", "charge_end", "death", "idle", "walk" },
    frozen_blaze = { "attack", "death", "spin" },
    gnut = { "attack", "death", "idle", "walk" },
    greatwhale = { "body", "dying", "jumpup", "swimming" },
    harmony_hare = { "back_kick", "death", "dodge", "jump_kick", "waiting", "waiting_pose", "walking" },
    ice_knight = { "body", "death", "death_mount", "dismount_mount", "horse_kicks_mount", "hurt", "hurt_mount", "idle", "idle_mount", "idle_mount_pose", "idle_pose", "raise_spear", "shockwave", "shockwave_mount", "slam_ice_pillars", "slash", "spawn_mount", "stab_forward", "stab_mount", "swipe_front_mount", "throw", "throw_dash_idle", "throw_finish", "walk", "walk_mount" },
    ["ice_knight-minion-shield"] = { "attack1", "attack2", "attack3", "body", "death", "idle", "walk" },
    ["ice_knight-minion-spear"] = { "attack1", "attack2", "attack3", "body", "death", "idle", "walk" },
    ["ice_knight-minion-sword"] = { "attack1", "attack2", "attack3", "body", "death", "idle", "walk" },
    ice_witch = { "attack", "attack2", "attack3", "death", "idle", "range_attack", "walk" },
    iceologer = { "attack", "attack2", "death", "idle", "walk" },
    leaf_storm = { "idle", "up" },
    leaf_tornado = { "idle" },
    lurking_lily = { "death", "hide", "idle", "idle_hiding", "show", "vine_attack1", "vine_attack2", "walk" },
    malevolent_moss = { "death", "hide", "idle", "idle_hiding", "show", "spit_attack", "walk" },
    mystic_stag = { "charge", "death", "dodgeleft", "dodgeright", "run", "waiting", "walking" },
    narwhal = { "bite", "body", "dying", "feedme", "feedstart", "nomnom", "swimming" },
    nectar_spider = { "bite", "cocoon", "death", "gas", "waiting", "walking", "web" },
    nocsy_dragon = { "bite", "death_fall", "death_ground", "falling", "fireball_air", "fireball_ground", "fireflame_air", "fireflame_ground", "fly", "grab", "idle", "idle_once", "walk", "wing_swing" },
    nocsy_dragon_saddled_version = { "bite", "death_fall", "death_ground", "falling", "fireball_air", "fireball_ground", "fireflame_air", "fireflame_ground", "fly", "grab", "idle", "idle_once", "walk", "wing_swing" },
    octopus = { "bite", "body", "dying", "ink", "swimming", "waiting" },
    poisonous_bloom = { "death", "eat", "escape", "gas_explode", "regen", "spore", "spore_splash", "waiting" },
    red_angler_fish = { "bite", "death", "idle", "walk" },
    rootling = { "attack1", "attack2", "death", "hurt", "hurt1", "idle", "walk" },
    snowball_spirit = { "charge", "idle", "walk" },
    undead_ice_warrior = { "attack", "death", "idle", "walk" },
    vfx_ground = { "spawn" },
    vfx_grumblegrassland_spore = { "idle", "walk" },
    vfx_grumblegrassland_spore_explode = { "actived", "spawn" },
    vfx_poison_smoke = { "spawn" },
    vfx_puff = { "idle", "spawn", "walk" },
    vfx_ring = { "spawn" },
    vfx_smash = { "idle", "spawn", "walk" },
    vfx_stomp = { "idle", "spawn", "walk" },
    ["vfx-ec-leviathan-bullet"] = { "death", "idle", "launch", "on_spawn", "run", "scales", "tail", "vortex", "walk", "wreck", "wreck_show" },
    ["vfx-ice_knight_blood_impact"] = { "spawn" },
    ["vfx-ice_knight_shock"] = { "spawn" },
    ["vfx-ice_knight_slash"] = { "spawn" },
    ["vfx-ice_knight_slash_2"] = { "spawn" },
    ["vfx-ice_knight_slash_hitfx"] = { "spawn" },
    ["vfx-ice_knight_summon"] = { "idle" },
    ["vfx-ice_pillar"] = { "idle", "spawn" },
    vivid_viper = { "ambush", "bite", "death", "idle", "pounce", "smoky_territory", "walk" },
    whispering_willow = { "animation.model.new", "death", "hornattack", "kick", "punch", "running", "spell", "waiting", "walking" },
    whispering_wisteria = { "dash_back", "death", "disappear", "idle", "lunge_idle", "lunge_slash", "walk" },
}

local function register_animation(entity_key, name)
    local ok, err = xpcall(function()
        local raw = aris.game.geckolib.create_animation(entity_key, name)
        raw:then_play(name)
    end, debug ~= nil and debug.traceback or tostring)
    if not ok then
        aris.log_error("[05_converted_missing_animations] " .. tostring(entity_key) .. ":" .. tostring(name) .. " " .. tostring(err))
    end
end

for entity_key, names in pairs(animations) do
    for _, name in ipairs(names) do
        register_animation(entity_key, name)
    end
end
