local sync_packet = aris.init.networking.create_s2c_packet("guild_sync")
sync_packet:append(aris.init.networking.integer_arg("in_guild"))
sync_packet:append(aris.init.networking.string_arg("name"))
sync_packet:append(aris.init.networking.integer_arg("level"))
sync_packet:append(aris.init.networking.integer_arg("exp"))
sync_packet:append(aris.init.networking.integer_arg("members"))
sync_packet:append(aris.init.networking.string_arg("owner"))
sync_packet:append(aris.init.networking.string_arg("member_names"))
sync_packet:append(aris.init.networking.string_arg("owner_name"))
sync_packet:append(aris.init.networking.integer_arg("has_invite"))

local action_packet = aris.init.networking.create_c2s_packet("guild_gui_action")
action_packet:append(aris.init.networking.string_arg("action"))
action_packet:append(aris.init.networking.string_arg("value"))
