local attr = aris.init.geckolib.entity_attr()
attr:max_health(20)
attr:attack_damage(2)
attr:armor(0)
attr:movement_speed(0.25)
attr:follow_range(16)

local vfx_attr = aris.init.geckolib.entity_attr()
vfx_attr:max_health(1000000)
vfx_attr:armor(1000000)
vfx_attr:movement_speed(0)
vfx_attr:follow_range(2048)

local entity_sizes = {
    aquamarine = { 1.0, 2.0 },
    ashen_azalea = { 1.0, 2.0 },
    beluga = { 1.0, 2.0 },
    black_angler_fish = { 1.0, 2.0 },
    bronze = { 1.0, 2.0 },
    cerberus = { 1.0, 2.0 },
    cocoon = { 1.0, 2.0 },
    deep_angler_fish = { 1.0, 2.0 },
    diamond = { 1.0, 2.0 },
    ecabyssosaurus = { 1.0, 2.0 },
    ecamonite = { 1.0, 2.0 },
    ecaquilolamna = { 1.0, 2.0 },
    ecaquilolamnababy = { 1.0, 2.0 },
    ecarchelon = { 1.0, 2.0 },
    ecatopodentatus = { 1.0, 2.0 },
    ecbabyaquilolamna = { 1.0, 2.0 },
    ecbabyelasmosaurus = { 1.0, 2.0 },
    ecbabymosasaurus = { 1.0, 2.0 },
    ecbabyophthalmosaurus = { 1.0, 2.0 },
    ecbabyplesiosaurus = { 1.0, 2.0 },
    ecbabyshastasaurus = { 1.0, 2.0 },
    eccartornychus = { 1.0, 2.0 },
    ecclidastes = { 1.0, 2.0 },
    eccoelacanth = { 1.0, 2.0 },
    eccogboundicarosphinx = { 1.0, 2.0 },
    ecdunkleosteus = { 1.0, 2.0 },
    ecdunkleosteusbaby = { 1.0, 2.0 },
    ecelasmosaurus = { 1.0, 2.0 },
    ecelasmosaurusbaby = { 1.0, 2.0 },
    ecichtyosaurus = { 1.0, 2.0 },
    ecleedsichthys = { 1.0, 2.0 },
    ecleviathan = { 1.0, 2.0 },
    ["ec-leviathan"] = { 1.0, 2.0 },
    ["ec-leviathan_seg"] = { 1.0, 2.0 },
    ecleviathanbaby = { 1.0, 2.0 },
    ecliopleurodon = { 1.0, 2.0 },
    ecliopleurodonbaby = { 1.0, 2.0 },
    ecmosasaurus = { 1.0, 2.0 },
    ecmosasaurusbaby = { 1.0, 2.0 },
    ecophthalmosaurus = { 1.0, 2.0 },
    ecplesiosaurus = { 1.0, 2.0 },
    ecplesiosaurusbaby = { 1.0, 2.0 },
    ecseascorpion = { 1.0, 2.0 },
    ecshastasaurus = { 1.0, 2.0 },
    ecshastasaurusbaby = { 1.0, 2.0 },
    em_dskeleton_archer = { 1.0, 2.0 },
    em_dskeleton_footman = { 1.0, 2.0 },
    em_dskeleton_halberdier = { 1.0, 2.0 },
    em_dskeleton_swordman = { 1.0, 2.0 },
    em_dskeleton_tank = { 1.0, 2.0 },
    em_dskeleton_variations = { 1.0, 2.0 },
    em_dskeleton_warrior = { 1.0, 2.0 },
    em_dskeleton_wizard = { 1.0, 2.0 },
    emerald = { 1.0, 2.0 },
    ent_guardian = { 1.0, 2.0 },
    ent_king = { 1.0, 2.0 },
    ent_minion = { 1.0, 2.0 },
    ent_sorcerer = { 1.0, 2.0 },
    ent_warrior = { 1.0, 2.0 },
    frostmite = { 1.0, 2.0 },
    frozen_blaze = { 1.0, 2.0 },
    garnet = { 1.0, 2.0 },
    gnut = { 1.0, 2.0 },
    gold = { 1.0, 2.0 },
    greatwhale = { 1.0, 2.0 },
    harmony_hare = { 1.0, 2.0 },
    ice_knight = { 1.0, 2.0 },
    ["ice_knight-minion-shield"] = { 1.0, 2.0 },
    ["ice_knight-minion-spear"] = { 1.0, 2.0 },
    ["ice_knight-minion-sword"] = { 1.0, 2.0 },
    ice_witch = { 1.0, 2.0 },
    iceologer = { 1.0, 2.0 },
    iron = { 1.0, 2.0 },
    lapis = { 1.0, 2.0 },
    lurking_lily = { 1.0, 2.0 },
    malevolent_moss = { 1.0, 2.0 },
    mystic_stag = { 1.0, 2.0 },
    narwhal = { 1.0, 2.0 },
    nectar_spider = { 1.0, 2.0 },
    nocsy_dragon = { 1.0, 2.0 },
    nocsy_dragon_saddled_version = { 1.0, 2.0 },
    obsidian = { 1.0, 2.0 },
    octopus = { 1.0, 2.0 },
    poison_targe = { 1.0, 2.0 },
    poisonous_bloom = { 1.0, 2.0 },
    red_angler_fish = { 1.0, 2.0 },
    redstone = { 1.0, 2.0 },
    rootling = { 1.0, 2.0 },
    ruby = { 1.0, 2.0 },
    sapphire = { 1.0, 2.0 },
    snowball_spirit = { 1.0, 2.0 },
    the_soulrot = { 1.0, 2.0 },
    undead_ice_warrior = { 1.0, 2.0 },
    vivid_viper = { 1.0, 2.0 },
    whispering_willow = { 1.0, 2.0 },
    whispering_wisteria = { 1.0, 2.0 },
}

local vfx_entities = {
    "circular_branch",
    "em_dskeleton_fire_resources",
    "em_dskeleton_firexplosion_marker",
    "em_dskeleton_firexplosion_vfx",
    "em_dskeleton_wizard_death",
    "em_dskeleton_wizardshield",
    "em_dsw_fireball",
    "ent_branch",
    "ent_branch_upwards",
    "leaf_storm",
    "leaf_tornado",
    "vfx_ground",
    "vfx_grumblegrassland_spore",
    "vfx_grumblegrassland_spore_explode",
    "vfx_poison_smoke",
    "vfx_puff",
    "vfx_ring",
    "vfx_smash",
    "vfx_stomp",
    "vfx-ec-leviathan-bullet",
    "vfx-ice_knight_blood_impact",
    "vfx-ice_knight_shock",
    "vfx-ice_knight_slash",
    "vfx-ice_knight_slash_2",
    "vfx-ice_knight_slash_hitfx",
    "vfx-ice_knight_summon",
    "vfx-ice_pillar",
}

for key, size in pairs(entity_sizes) do
    aris.init.geckolib.create_entity(key, size[1], size[2], attr)
end

for _, key in ipairs(vfx_entities) do
    aris.init.geckolib.create_entity(key, 0.1, 0.1, vfx_attr)
end
