local attr = aris.init.geckolib.entity_attr()
attr:max_health(20)
attr:attack_damage(2)
attr:armor(0)
attr:movement_speed(0.25)
attr:follow_range(16)

local entity_health = {
    ashen_azalea = 30,
    beluga = 70,
    black_angler_fish = 32,
    deep_angler_fish = 32,
    ecabyssosaurus = 300,
    ecamonite = 30,
    ecaquilolamna = 300,
    ecaquilolamnababy = 300,
    ecarchelon = 100,
    ecatopodentatus = 100,
    ecbabyaquilolamna = 300,
    ecbabyelasmosaurus = 300,
    ecbabymosasaurus = 150,
    ecbabyophthalmosaurus = 300,
    ecbabyplesiosaurus = 300,
    ecbabyshastasaurus = 150,
    eccartornychus = 100,
    ecclidastes = 300,
    eccoelacanth = 30,
    eccogboundicarosphinx = 1000,
    ecdunkleosteus = 300,
    ecdunkleosteusbaby = 100,
    ecelasmosaurus = 300,
    ecelasmosaurusbaby = 300,
    ecichtyosaurus = 300,
    ecleedsichthys = 600,
    ecleviathan = 600,
    ["ec-leviathan"] = 500,
    ecleviathanbaby = 150,
    ecliopleurodon = 600,
    ecliopleurodonbaby = 150,
    ecmosasaurus = 600,
    ecmosasaurusbaby = 150,
    ecophthalmosaurus = 300,
    ecplesiosaurus = 300,
    ecplesiosaurusbaby = 300,
    ecseascorpion = 30,
    ecshastasaurus = 600,
    ecshastasaurusbaby = 150,
    em_dskeleton_archer = 30,
    em_dskeleton_footman = 20,
    em_dskeleton_halberdier = 30,
    em_dskeleton_swordman = 26,
    em_dskeleton_tank = 66,
    em_dskeleton_warrior = 36,
    em_dskeleton_wizard = 45,
    ent_guardian = 200,
    ent_king = 350,
    ent_minion = 15,
    ent_sorcerer = 25,
    ent_warrior = 30,
    greatwhale = 200,
    harmony_hare = 30,
    ice_knight = 200,
    ["ice_knight-minion-shield"] = 120,
    ["ice_knight-minion-spear"] = 50,
    ["ice_knight-minion-sword"] = 80,
    lurking_lily = 100,
    malevolent_moss = 100,
    mystic_stag = 30,
    narwhal = 50,
    nectar_spider = 60,
    nocsy_dragon = 800,
    nocsy_dragon_saddled_version = 800,
    octopus = 130,
    poisonous_bloom = 500,
    red_angler_fish = 32,
    rootling = 20,
    the_soulrot = 100,
    vivid_viper = 60,
    whispering_willow = 100,
    whispering_wisteria = 100,
}

local function create_default_attr(key)
    local attr = aris.init.geckolib.entity_attr()
    attr:max_health(entity_health[key] or 20)
    attr:attack_damage(2)
    attr:armor(0)
    attr:movement_speed(0.25)
    attr:follow_range(16)
    return attr
end

local vfx_attr = aris.init.geckolib.entity_attr()
vfx_attr:max_health(1856794)
vfx_attr:armor(1000000)
vfx_attr:movement_speed(0)
vfx_attr:follow_range(2048)

local entity_sizes = {
    aquamarine = { 1, 2.5 },
    ashen_azalea = { 6, 11.5 },
    beluga = { 4.5, 3 },
    black_angler_fish = { 1.5, 2.5 },
    bronze = { 1, 2.5 },
    cerberus = { 6, 9.5 },
    cocoon = { 1.5, 3.5 },
    deep_angler_fish = { 1.5, 2.5 },
    diamond = { 1, 2.5 },
    ecabyssosaurus = { 6, 3.5 },
    ecamonite = { 1.5, 3.5 },
    ecaquilolamna = { 6, 6 },
    ecaquilolamnababy = { 3.5, 2.5 },
    ecarchelon = { 6, 3.5 },
    ecatopodentatus = { 4, 2.5 },
    ecbabyaquilolamna = { 3.5, 2.5 },
    ecbabyelasmosaurus = { 3.5, 2.5 },
    ecbabymosasaurus = { 6, 2.5 },
    ecbabyophthalmosaurus = { 2, 2.5 },
    ecbabyplesiosaurus = { 2.5, 2.5 },
    ecbabyshastasaurus = { 4.5, 2.5 },
    eccartornychus = { 5, 2.5 },
    ecclidastes = { 6, 3.5 },
    eccoelacanth = { 2.5, 2.5 },
    eccogboundicarosphinx = { 6, 15.5 },
    ecdunkleosteus = { 6, 7 },
    ecdunkleosteusbaby = { 4, 3.5 },
    ecelasmosaurus = { 6, 3.5 },
    ecelasmosaurusbaby = { 3.5, 2.5 },
    ecichtyosaurus = { 4, 2.5 },
    ecleedsichthys = { 6, 11 },
    ecleviathan = { 6, 9.5 },
    ["ec-leviathan"] = { 6, 3 },
    ["ec-leviathan_seg"] = { 6, 8 },
    ecleviathanbaby = { 6, 3.5 },
    ecliopleurodon = { 6, 6.5 },
    ecliopleurodonbaby = { 4, 3 },
    ecmosasaurus = { 6, 12 },
    ecmosasaurusbaby = { 6, 2.5 },
    ecophthalmosaurus = { 5.5, 3.5 },
    ecplesiosaurus = { 5, 2.5 },
    ecplesiosaurusbaby = { 2.5, 2.5 },
    ecseascorpion = { 5.5, 2.5 },
    ecshastasaurus = { 6, 5.5 },
    ecshastasaurusbaby = { 4.5, 2.5 },
    em_dskeleton_archer = { 2, 3.5 },
    em_dskeleton_footman = { 1, 3.5 },
    em_dskeleton_halberdier = { 2, 3.5 },
    em_dskeleton_swordman = { 1, 3.5 },
    em_dskeleton_tank = { 2, 3.5 },
    em_dskeleton_variations = { 1, 5 },
    em_dskeleton_warrior = { 1.5, 3.5 },
    em_dskeleton_wizard = { 2, 3.5 },
    emerald = { 1, 2.5 },
    ent_guardian = { 4.5, 6.5 },
    ent_king = { 3, 6.5 },
    ent_minion = { 1, 2.5 },
    ent_sorcerer = { 2, 3.5 },
    ent_warrior = { 2.5, 3.5 },
    frostmite = { 3, 3.5 },
    frozen_blaze = { 1.5, 3.5 },
    garnet = { 1, 2.5 },
    gnut = { 1.5, 3.5 },
    gold = { 1, 2.5 },
    greatwhale = { 6, 6 },
    harmony_hare = { 1, 2.5 },
    ice_knight = { 3.5, 6.5 },
    ["ice_knight-minion-shield"] = { 1.5, 3.5 },
    ["ice_knight-minion-spear"] = { 1.5, 3.5 },
    ["ice_knight-minion-sword"] = { 1.5, 3.5 },
    ice_witch = { 1.5, 3.5 },
    iceologer = { 1.5, 3.5 },
    iron = { 1, 2.5 },
    lapis = { 1, 2.5 },
    lurking_lily = { 4, 4.5 },
    malevolent_moss = { 2, 6 },
    mystic_stag = { 2.5, 4.5 },
    narwhal = { 4, 3 },
    nectar_spider = { 2.5, 3.5 },
    nocsy_dragon = { 6, 7 },
    nocsy_dragon_saddled_version = { 6, 6.5 },
    obsidian = { 1, 2.5 },
    octopus = { 1.5, 2.5 },
    poison_targe = { 1, 1.5 },
    poisonous_bloom = { 5, 8.5 },
    red_angler_fish = { 1.5, 2.5 },
    redstone = { 1, 2.5 },
    rootling = { 1.5, 2.5 },
    ruby = { 1, 2.5 },
    sapphire = { 1, 2.5 },
    snowball_spirit = { 1.5, 1.5 },
    the_soulrot = { 6, 6.5 },
    undead_ice_warrior = { 3, 4.5 },
    vivid_viper = { 6, 2.5 },
    whispering_willow = { 2, 4.5 },
    whispering_wisteria = { 2.5, 4.5 },
}

local entity_hitbox_height = {
    aquamarine = 2,
    ashen_azalea = 11,
    beluga = 2,
    black_angler_fish = 2,
    bronze = 2,
    cerberus = 9,
    cocoon = 3,
    deep_angler_fish = 2,
    diamond = 2,
    ecabyssosaurus = 3,
    ecamonite = 3,
    ecaquilolamna = 5,
    ecaquilolamnababy = 2,
    ecarchelon = 3,
    ecatopodentatus = 2,
    ecbabyaquilolamna = 2,
    ecbabyelasmosaurus = 2,
    ecbabymosasaurus = 2,
    ecbabyophthalmosaurus = 2,
    ecbabyplesiosaurus = 2,
    ecbabyshastasaurus = 2,
    eccartornychus = 2,
    ecclidastes = 3,
    eccoelacanth = 2,
    eccogboundicarosphinx = 15,
    ecdunkleosteus = 6,
    ecdunkleosteusbaby = 3,
    ecelasmosaurus = 3,
    ecelasmosaurusbaby = 2,
    ecichtyosaurus = 2,
    ecleedsichthys = 10,
    ecleviathan = 9,
    ["ec-leviathan"] = 2,
    ["ec-leviathan_seg"] = 7,
    ecleviathanbaby = 3,
    ecliopleurodon = 6,
    ecliopleurodonbaby = 2,
    ecmosasaurus = 10,
    ecmosasaurusbaby = 2,
    ecophthalmosaurus = 3,
    ecplesiosaurus = 2,
    ecplesiosaurusbaby = 2,
    ecseascorpion = 2,
    ecshastasaurus = 5,
    ecshastasaurusbaby = 2,
    em_dskeleton_archer = 3,
    em_dskeleton_footman = 3,
    em_dskeleton_halberdier = 3,
    em_dskeleton_swordman = 3,
    em_dskeleton_tank = 3,
    em_dskeleton_variations = 4,
    em_dskeleton_warrior = 3,
    em_dskeleton_wizard = 3,
    emerald = 2,
    ent_guardian = 6,
    ent_king = 6,
    ent_minion = 2,
    ent_sorcerer = 3,
    ent_warrior = 3,
    frostmite = 3,
    frozen_blaze = 3,
    garnet = 2,
    gnut = 3,
    gold = 2,
    greatwhale = 5,
    harmony_hare = 2,
    ice_knight = 6,
    ["ice_knight-minion-shield"] = 3,
    ["ice_knight-minion-spear"] = 3,
    ["ice_knight-minion-sword"] = 3,
    ice_witch = 3,
    iceologer = 3,
    iron = 2,
    lapis = 2,
    lurking_lily = 4,
    malevolent_moss = 5,
    mystic_stag = 4,
    narwhal = 2,
    nectar_spider = 3,
    nocsy_dragon = 6,
    nocsy_dragon_saddled_version = 6,
    obsidian = 2,
    octopus = 2,
    poison_targe = 1,
    poisonous_bloom = 8,
    red_angler_fish = 2,
    redstone = 2,
    rootling = 2,
    ruby = 2,
    sapphire = 2,
    snowball_spirit = 1,
    the_soulrot = 6,
    undead_ice_warrior = 4,
    vivid_viper = 2,
    whispering_willow = 4,
    whispering_wisteria = 4,
}

local vfx_entities = {
    "circular_branch",
    "em_dskeleton_fire_resources",
    "em_dskeleton_firexplosion_marker",
    "em_dskeleton_firexplosion_vfx",
    "em_dskeleton_wizard_death",
    "em_dskeleton_wizardshield",
    "em_dsw_fireball",
    "ent_branch",
    "ent_branch_upwards",
    "leaf_storm",
    "leaf_tornado",
    "vfx_ground",
    "vfx_grumblegrassland_spore",
    "vfx_grumblegrassland_spore_explode",
    "vfx_poison_smoke",
    "vfx_puff",
    "vfx_ring",
    "vfx_smash",
    "vfx_stomp",
    "vfx-ec-leviathan-bullet",
    "vfx-ice_knight_blood_impact",
    "vfx-ice_knight_shock",
    "vfx-ice_knight_slash",
    "vfx-ice_knight_slash_2",
    "vfx-ice_knight_slash_hitfx",
    "vfx-ice_knight_summon",
    "vfx-ice_pillar",
}

local function create_entity_with_hitbox(key, size)
    aris.init.geckolib.create_entity(key, size[1], entity_hitbox_height[key] or size[2], create_default_attr(key))
end

for key, size in pairs(entity_sizes) do
    create_entity_with_hitbox(key, size)
end

for _, key in ipairs(vfx_entities) do
    aris.init.geckolib.create_entity(key, 0.1, 0.1, vfx_attr)
end
